name: GitHub Code Quality Analyzer
description: "Analyzes code quality based on DRY and SOLID principles."
inputs:
  repo:
    description: "GitHub repository to analyze (e.g., owner/repo)"
    required: true
  openai_api_key:
    description: "API key for OpenAI"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"