analysis:
  dry:
    enabled: true
    weight: 0.7
    focus_areas:
      logic_reuse: 0.4
      data_centralization: 0.3
      abstraction_level: 0.3
    severity_threshold: 0.7

  solid:
    enabled: true
    weight: 0.3
    principles:
      srp:
        enabled: true
        weight: 0.3
      ocp:
        enabled: true
        weight: 0.2
      lsp:
        enabled: false
      isp:
        enabled: false
      dip:
        enabled: true
        weight: 0.5
    severity_threshold: 0.6

prompt_customization:
  context_depth: "medium"
  language_specificity: "python"
  explanation_detail: "high"
  temperature: 0.3
  max_tokens: 500

feedback_format:
  include_dry_score: true
  include_solid_score: true
  message_template: |
    ## Analysis for {file}

    ### DRY Score: {dry_score}/10
    {dry_analysis}

    ### SOLID Score: {solid_score}/10
    {solid_analysis}